version: '3'

networks:
  proxynginx:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxynginx

  web-blue-01:
    image: fabricioveronez/web-page:blue
    # ports: 
    #   - 7071:80
    networks:
      - proxynginx
  
  web-blue-02:
    image: fabricioveronez/web-page:blue
    networks:
      - proxynginx

  web-green-01:
    image: fabricioveronez/web-page:green
    # ports: 
    #   - 7072:80
    networks:
      - proxynginx

  web-green-02:
    image: fabricioveronez/web-page:green
    networks:
      - proxynginx